---
- hosts: app
  # gather_facts: true
  become: true
  tasks:
    - name: Clone app from git
      git:
        repo: https://github.com/ali-tm-amin/Eng99App.git
        dest: /home/ubuntu/app
        clone: yes
        update: yes

- name: Install DB
  import_playbook: mongo.yml

- name: Install app
  import_playbook: nginx.yml

- name: Install app
  import_playbook: nodejs.yml