---
- hosts: app
  gather_facts: true
  become: true
  tasks:
  - name: Update and Upgrade
    shell: sudo apt-get update -y && sudo apt-get upgrade -y

  - name: Install Git
    shell: sudo apt-get install git -y

  - name: remove repo
    shell: rm -rf terraform

  # - name: Clone Repo
  #   shell: git clone https://github.com/ali-tm-amin/eng99_jenkins_terraform.git
  #   #cd eng99_jenkins_terraform/
  #   #cd app/

  - name: run the provisioning file
    shell: chmod +x app_provision.sh && ./app_provision.sh
    
  