# mongo.yml
# Note - Ensure the node-app and mongodb required dependencies are available in the specified location

---

- hosts: db

  gather_facts: yes

  become: true
  tasks:
  - name:
    shell: |
      sudo apt-get update -y
      sudo apt-get upgrade -y
    become_user: root  
      
  - name: Installing mongodb in db VM
    apt: pkg=mongodb state=present
  - name: Modify Mongod.conf file, update BindIP to be 0.0.0.0
    lineinfile:
      path: /etc/mongodb.conf
      regexp: '^bind_ip'                                                                                     
      line: 'bind_ip = 0.0.0.0'                                                                            
      backrefs: yes                                                                                    
  - name: Restart and enable mongodb
    shell: sudo systemctl restart mongodb && sudo systemctl enable mongodb

  # - name: restarting db and chnaging conf file
  #   shell: |
  #     git clone https://github.com/Delwar35/awsFileTransfer
  #     sudo rm -rf /etc/mongod.conf
  #     sudo cp ./mongod.conf /etc/mongod.conf
  #     sudo systemctl restart mongodb
  #     sudo systemctl enable mongodb
    become_user: root

  # tasks:
  # - name: install mongodb
  #   apt: pkg=mongodb state=present

  # - name: Remove mongodb file (delete file)
  #   file:
  #     path: /etc/mongodb.conf
  #     state: absent

  # - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
  #   file:
  #     path: /etc/mongodb.conf
  #     state: touch
  #     mode: u=rw,g=r,o=r

