---
# Which host do we need to install nginx in
- hosts: app

# What facts do we want to see whilst installing
  gather_facts: true

# Do we need admin access? yes
  become: true

# What task do we want to perform in this yml file?
  tasks:
  - name: Install Nginx in web agent node
    apt: pkg=nginx state=present
    become_user: root

  # - name: Ansible copy file to remote server
  #   copy:
  #     src: /etc/ansible/default
  #     dest: /etc/nginx/sites-available/default
# what is the end goal for this task
# nginx status running

  # - name: restart nginx
  #   service: name=nginx state=restarted