---
# Which host do we need to install nginx in
- hosts: app

# What facts do we want to see whilst installing
  gather_facts: true

# Do we need admin access? yes
  become: true

# What task do we want to perform in this yml file?
  tasks:
  - name: Install Nginx in web agent node
    apt: pkg=nginx state=present
    become_user: root

  # - name: Setting reverse proxy
  #     shell: |
  #       git clone https://github.com/Delwar35/awsFileTransfer
  #       sudo rm -rf /etc/nginx/sites-available/default
  #       cp ./awsFileTransfer/default /etc/nginx/sites-available/default
  #     become_user: root

  # - name: Restart Ngnix
  #   shell: |
  #     sudo systemctl restart nginx
  #   become_user: root