
- hosts: app
  gather_facts: true
  become: true
  tasks:
  - name: Install Nodejs in web Agent Node
    shell: |
      curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - && sudo apt-get install nodejs -y
  # - name: install nodejs
  #   apt: pkg=nodejs state=present
    become_user: root

#  - name: Install NPM
#    shell: |
#      install npm
    #apt: pkg=npm state=present


  - name: Clone git
    git:
      repo: https://github.com/ali-tm-amin/Eng99App.git
      dest: /home/vagrant/app
      clone: yes
      update: yes

  - name: download latest npm + Mongoose
    shell: |
      apt install npm -y
      npm install -g npm@latest
      npm install mongoose -y
      npm install express -y
      set NODE_PATH=app/seeds/seed.js;%NODE_PATH%
    become_user: root
  # Downloading pm2
  - name: Install pm2
    npm:
      name: pm2
      global: yes
  - name: env variable
    shell: |
      echo 'export DB_HOST="mongodb://34.244.178.76:27017/posts"' >> .bashrc
  - name: seed + run app
    shell: |
      #cd awsFileTransfer/
      cp -R app/seeds home/ubuntu/seeds
      cd app/
      npm install
      node seeds/seed.js
      #pm2 kill
      #pm2 start app.js


